In [1]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.offline as pyo
import plotly.figure_factory as ff
from plotly.offline import init_notebook_mode, iplot, download_plotlyjs

import tensorflow as tf

import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
df = pd.read_csv("../data/Admission_Predict.csv")
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

In [3]:
df.rename(columns = {'Chance of Admit ':'Chance of Admit', 'LOR ':'LOR'}, inplace=True)
df.drop(labels='Serial No.', axis=1, inplace=True)

In [4]:
targets = df['Chance of Admit']
features = df.drop(columns = {'Chance of Admit'})

X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)

In [5]:
X_train.shape

(320, 7)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [7]:
X_train=tf.constant(X_train,dtype=tf.float32)
y_train=tf.constant(y_train,dtype=tf.float32)
X_test=tf.constant(X_test,dtype=tf.float32)
y_test=tf.constant(y_test,dtype=tf.float32)

In [8]:
X_train[0].shape

TensorShape([7])

In [9]:
tf.random.set_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.Dense(5,input_shape=[7],name="input_layer"),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(20),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1,name="output_layer")
])

model.compile(loss=tf.keras.losses.mae,
             optimizer=tf.keras.optimizers.SGD(),
              metrics=["mae"]
             )

model.fit(X_train,y_train,epochs=100)

Epoch 1/100
10/10 [==============================] - 0s 1ms/step - loss: 0.6388 - mae: 0.6388
Epoch 2/100
10/10 [==============================] - 0s 1ms/step - loss: 0.2499 - mae: 0.2499
Epoch 3/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0691 - mae: 0.0691
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0739 - mae: 0.0739
Epoch 5/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0928 - mae: 0.0928
Epoch 6/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0790 - mae: 0.0790
Epoch 7/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0742 - mae: 0.0742
Epoch 8/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0614 - mae: 0.0614
Epoch 9/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0739 - mae: 0.0739
Epoch 10/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0761 - mae: 0.0761
Epoch 11/100
10/10 [==============================] - 0s 1m

10/10 [==============================] - 0s 2ms/step - loss: 0.0514 - mae: 0.0514
Epoch 87/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0511 - mae: 0.0511
Epoch 88/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0463 - mae: 0.0463
Epoch 89/100
10/10 [==============================] - 0s 889us/step - loss: 0.0419 - mae: 0.0419
Epoch 90/100
10/10 [==============================] - 0s 889us/step - loss: 0.0457 - mae: 0.0457
Epoch 91/100
10/10 [==============================] - 0s 889us/step - loss: 0.0483 - mae: 0.0483
Epoch 92/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0478 - mae: 0.0478
Epoch 93/100
10/10 [==============================] - 0s 889us/step - loss: 0.0448 - mae: 0.0448
Epoch 94/100
10/10 [==============================] - 0s 778us/step - loss: 0.0509 - mae: 0.0509
Epoch 95/100
10/10 [==============================] - 0s 667us/step - loss: 0.0493 - mae: 0.0493
Epoch 96/100
10/10 [==============================]

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_layer (Dense)          (None, 5)                 40        
_________________________________________________________________
dense (Dense)                (None, 10)                60        
_________________________________________________________________
dense_1 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_2 (Dense)              (None, 10)                210       
_________________________________________________________________
output_layer (Dense)         (None, 1)                 11        
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________


In [11]:
y_preds=model.predict(X_test).reshape(1,80)[0]
y_preds.shape

(80,)

In [12]:
y_true=np.array(y_test)

In [13]:
from sklearn.metrics import accuracy_score


In [14]:
type(y_preds)

numpy.ndarray

In [15]:
model.evaluate(X_test, y_test)

3/3 [==============================] - 0s 4ms/step - loss: 0.0503 - mae: 0.0503


[0.05033842846751213, 0.05033842846751213]

In [16]:
X_test[0]

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-1.285543  , -0.5259433 , -0.1553256 , -0.0200129 ,  0.5968194 ,
       -0.8381837 ,  0.83793056], dtype=float32)>

In [22]:
model.predict(X_test)[0]

array([0.6501674], dtype=float32)

In [21]:
y_test[0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.68>